### ISSUE TITLE
Mismatch between transcription and audios.

### ISSUE THREAD

**Issue by rafaelvalle** [Tomiinek/Blizzard2013_Segmentation#2]
Thank you for making this extremely useful repo available!

There's a mismatch between transcription and audios at least for the books ethan_frome, the_emerald_city_of_oz and the_patchwork_girl_of_oz. 

The transcription (01.txt) starts at the chapters while for some books the audio (01.wav) starts at the prologue or something else that doesn't match the transcription.

A temporary fix is to rename the files, decreasing each file's numbering by one
```rename -n 's/(\d{2,3}).wav/sprintf("temp\/%02d", $1-1) . ".wav"/e' *.wav```

**Comment by rafaelvalle** [comment]
I just realized you never provided the audio :-)

**Comment by Tomiinek** [comment]
Hello, thank you @rafaelvalle!

Do you think there should be a suggestion in the repo README for removing some chapters (prologues) for the particular books?
